### ISSUE TITLE
Using modules in haptics-playground-main.html doesn't always work

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/quake#11] opened 2022-04-05 21:12 UTC
On my machine, using JavaScript modules causes a runtime error for the cordova app. In order to build and run quake I have to make these changes to stop using modules:

```patch
Index: www/haptics-playground.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/www/haptics-playground.html b/www/haptics-playground.html
--- a/www/haptics-playground.html	(revision 700d36942683fcdc3565b6f0921ac5511faacbb3)
+++ b/www/haptics-playground.html	(date 1649188619000)
@@ -145,6 +145,6 @@
 </div>
 
 <script src="cordova.js"></script>
-<script type="module" src="js/haptics-playground-main.js"></script>
+<script src="js/haptics-playground-main.js"></script>
 </body>
 </html>
Index: www/js/haptics-playground-main.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/www/js/haptics-playground-main.js b/www/js/haptics-playground-main.js
--- a/www/js/haptics-playground-main.js	(revision 700d36942683fcdc3565b6f0921ac5511faacbb3)
+++ b/www/js/haptics-playground-main.js	(date 1649188378717)
@@ -6,7 +6,7 @@
  * @author John Blanco (PhET Interactive Simulations)
  */
 
-import ScreenDebugLogger from './ScreenDebugLogger.js';
+// import ScreenDebugLogger from './ScreenDebugLogger.js';
 
 // constants
 const NOOP = () => {};
@@ -26,7 +26,7 @@
   console.log( `Running cordova-${cordova.platformId}@${cordova.version}` );
 
   // Create the logger that will output debug messages to the app's screen.
-  const logger = new ScreenDebugLogger();
+  const logger = console;
 
   //--------------------------------------------------------------------------------------------------------------------
   // Set up the "Clicks" screen.

```
But this isn't required on @jbphet's setup. Documenting it here so we remember what needs to change when I need to build quake, and maybe to investigate what needs to change about my cordova setup so that I can use modules if there is time.

**Comment by jbphet** [comment] 2022-05-09 20:22
I forgot this issue existed and create a duplicate, see https://github.com/phetsims/quake/issues/16.  The problem is now resolved, please see the other issue for details.  Closing.

**Closed as completed by jbphet** 2022-05-09 20:22 UTC
